package com.zap.maintenance.vo.enumerates;

/**
 * Autogenerated enumeration HashEnum.
 *
 * 
 */
public enum HashEnum implements java.io.Serializable
{
    /**
     *  
     */
    MD5,

    /**
     *  
     */
    SHA1,

    /**
     *  
     */
    SHA256,

    /**
     *  
     */
    SHA384,

    /**
     *  
     */
    SHA512,

    /**
     *  
     */
    BLOWFISH;

    /**
     * HashEnum constructor
     */
    private HashEnum()
    {
    }

    /**
     * Return the HashEnum from a string value
     * @return HashEnum enum object
     */
    public static HashEnum fromString(java.lang.String value)
    {
        return valueOf(value);
    }
    
    /**
     * Return a Collection of all literal values for this enumeration
     * @return java.util.Collection literal values
     */
    public static java.util.Collection<String> literals()
    {
        final java.util.Collection<String> literals = new java.util.ArrayList<String>(values().length);
        for (int i = 0; i < values().length; i++)
        {
            literals.add(values()[i].name());
        }
        return literals;
    }
}